출처:https://wikidocs.net/52460

<h4>넘파이로 텐서 만들기(벡터와 행렬 만들기)</h4>  


In [1]:
import numpy as np

t = np.array([0.,1.,2.,3.,4.,5.,6.])
#list를 생성하여 np.array로 1차원 array로 변환하는것과 같음
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [2]:
print('Rank of t:',t.ndim)#몇차원인지 출력함
print('Shape of t:',t.shape)#크기를 출력함 (7,)은 (1,7)을 의미하며 다시말해 (1x7)의 크기를 갖는 벡터임

Rank of t: 1
Shape of t: (7,)


<h5>1-1) Numpy 기초 이해하기</h5>
numpy에서 인덱스는 0 부터 시작한다.

In [4]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # 인덱스를 통한 원소 접근
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1]) # [시작 번호 : 끝 번호]로 범위 지정을 통해 가져온다. slicing
print('t[:2] t[3:]     = ', t[:2], t[3:]) # 시작 번호를 생략한 경우와 끝 번호를 생략한 경우


t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


<h5>2D with Numpy</h5>

In [5]:
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [6]:
print('Rank of t: ',t.ndim)
print('Shape of t: ',t.shape)

Rank of t:  2
Shape of t:  (4, 3)


<h4>3.파이토치 텐서 선언하기</h4>

In [7]:
import torch

<h5>1) 1D with Pytorch</h5>

In [8]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [9]:
#dim()을 사용하면 현재 텐서의 차원을 보여줌. shape나 size()를 사용하면 크기를 확인할 수 있다.
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


현재 1차원 텐서이며, 원소는 7개입니다. 인덱스로 접근하는 것과 슬라이싱을 해봅시다. 방법은 Numpy 실습과 같습니다.



In [10]:
print(t[0],t[1],t[-1])
print(t[2:5],t[4:-1])
print(t[:2],t[:3])

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([0., 1., 2.])


<h5>2) 2D with Pytorch</h5>

In [11]:
t = torch.FloatTensor([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [12]:
print(t.dim()) #rank. 즉 차원
print(t.size()) # shape

2
torch.Size([4, 3])


In [16]:
print(t[:,1]) #첫번째 차원을 전체 선택한 상황에서(:) 두번째 차원의 첫번째 것만 가져옴
print(t[:,1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [17]:
print(t[:,:-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


<h4>브로드캐스팅</h4>
두 행렬 A, B가 있다고 해봅시다. 행렬의 덧셈과 뺄셈에 대해 알고계신다면, 이 덧셈과 뺄셈을 할 때에는 두 행렬 A, B의 크기가 같아야한다는 것을 알고계실겁니다. 그리고 두 행렬이 곱셈을 할 때에는 A의 마지막 차원과 B의 첫번째 차원이 일치해야합니다.

물론, 이런 규칙들이 있지만 딥 러닝을 하게되면 불가피하게 크기가 다른 행렬 또는 텐서에 대해서 사칙 연산을 수행할 필요가 있는 경우가 생깁니다. 이를 위해 파이토치에서는 자동으로 크기를 맞춰서 연산을 수행하게 만드는 브로드캐스팅이라는 기능을 제공합니다

In [19]:
m1 = torch.FloatTensor([3,3])
m2 = torch.FloatTensor([2,2])
print(m1+m2)

tensor([5., 5.])


여기서 m1,과 m2의 크기는 둘 다 (1, 2)입니다. 그래서 문제없이 덧셈 연산이 가능합니다. 이번에는 크기가 다른 텐서들 간의 연산을 보겠습니다. 아래는 벡터와 스칼라가 덧셈 연산을 수행하는 것을 보여줍니다. 물론, 수학적으로는 원래 연산이 안 되는게 맞지만 파이토치에서는 브로드캐스팅을 통해 이를 연산합니다.

In [22]:
#Vector+Scalar
m1 = torch.FloatTensor([[1,2]])#2차원 = 벡터
m2 = torch.FloatTensor([3])#[3] -> [3,3] # 1차원 = Scalar
print(m1+m2)


tensor([[4., 5.]])


In [25]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1,2]]) #1,2
print(m1.size())
m2 = torch.FloatTensor([[3],[4]])#2,1
print(m2.size())
print(m1+m2)
# m1의 크기는 (1, 2) m2의 크기는 (2, 1)였습니다. 이 두 벡터는 원래 수학적으로는 덧셈을 수행할 수 없습니다. 
# 그러나 파이토치는 두 벡터의 크기를 (2, 2)로 변경하여 덧셈을 수행합니다.

torch.Size([1, 2])
torch.Size([2, 1])
tensor([[4., 5.],
        [5., 6.]])


브로드캐스팅은 편리하지만, 자동으로 실행되는 기능이므로 사용자 입장에서 굉장히 주의해서 사용해야 합니다. 예를 들어 A 텐서와 B 텐서가 있을 때, 사용자는 이 두 텐서의 크기가 같다고 착각하고 덧셈 연산을 수행했다고 가정해보겠습니다. 하지만 실제로 이 두 텐서의 크기는 달랐고 브로드캐스팅이 수행되어 덧셈 연산이 수행되었습니다. 만약, 두 텐서의 크기가 다르다고 에러를 발생시킨다면 사용자는 이 연산이 잘못되었음을 바로 알 수 있지만 브로드캐스팅은 자동으로 수행되므로 사용자는 나중에 원하는 결과가 나오지 않았더라도 어디서 문제가 발생했는지 찾기가 굉장히 어려울 수 있습니다.

<h4>자주 사용되는 기능들</h4>
<h5>1) 행렬 곱셈과 곱셈의 차이</h5>
행렬로 곱셈을 하는 방법은 크게 두 가지가 있습니다. 바로 행렬 곱셈(.matmul)과 원소 별 곱셈(.mul)입니다.
파이토치 텐서의 행렬 곱셈을 보겠습니다. 이는 matmul()을 통해 수행합니다.

In [27]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1)
print(m2)
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1.],
        [2.]])
tensor([[ 5.],
        [11.]])


위의 결과는 2 x 2 행렬과 2 x 1 행렬(벡터)의 행렬 곱셈의 결과를 보여줍니다.

행렬 곱셈이 아니라 element-wise 곱셈이라는 것이 존재합니다. 이는 동일한 크기의 행렬이 동일한 위치에 있는 원소끼리 곱하는 것을 말합니다. 아래는 서로 다른 크기의 행렬이 브로드캐스팅이 된 후에 element-wise 곱셈이 수행되는 것을 보여줍니다. 이는 * 또는 mul()을 통해 수행합니다.

In [29]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1)
print(m2)
print('//////')
print(m1 * m2) # 2 x 2 #element-wise
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1.],
        [2.]])
//////
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


<h5>평균</h5>
우선 1차원인 벡터를 선언하여 .mean()을 사용하여 원소의 평균을 구한다.

In [30]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [31]:
#이번에는 1차원을 구해보즈아
t= torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [32]:
print(t.mean())

tensor(2.5000)


In [33]:
#이번에는 dim. 즉, 차원을 인자로 주는 경우를 살펴보자
print(t.mean(dim=0))

tensor([2., 3.])


dim=0이라는 것은 첫번째 차원을 의미합니다. 행렬에서 첫번째 차원은 '행'을 의미합니다. 그리고 인자로 dim을 준다면 해당 차원을 제거한다는 의미가 됩니다. 다시 말해 행렬에서 '열'만을 남기겠다는 의미가 됩니다. 기존 행렬의 크기는 (2, 2)였지만 이를 수행하면 열의 차원만 보존되면서 (1, 2)가 됩니다. 이는 (2,)와 같으며 벡터입니다.

이번에는 인자로 dim=1을 주겠습니다. 이번에는 두번째 차원을 제거합니다. 즉, 열이 제거된 텐서가 되어야 합니다.



In [34]:
print(t.mean(dim=1))

tensor([1.5000, 3.5000])


<h5>덧셈</h5>


In [36]:
t= torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [38]:
print(t.sum())
print(t.sum(dim=0)) #행을 제거 => 같은 열끼리 연산.
print(t.sum(dim=1)) #열을 제거 => 같은 행끼리 연산
print(t.sum(dim=-1)) #열을 제거 => 같은 행끼리 연산

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


<h5>4)최대와 아그맥스</h5>
최대(Max)는 원소의 최대값을 리턴하고, 아그맥스(ArgMax)는 최대값을 가진 인덱스를 리턴합니다.
(2, 2) 크기의 행렬을 선언하고 Max를 사용해봅시다.

In [39]:
t= torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [41]:
print(t.max())

tensor(4.)


원소 중 최대값인 4를 리턴합니다.
이번에는 인자로 dim=0을 주겠습니다. 첫번째 차원을 제거한다는 의미입니다.

In [42]:
print(t.max(dim=0))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


그런데 [1, 1]이라는 값도 함께 리턴되었습니다. max에 dim 인자를 주면 argmax도 함께 리턴하는 특징 때문입니다. 첫번째 열에서 3의 인덱스는 1이었습니다. 두번째 열에서 4의 인덱스는 1이었습니다. 그러므로 [1, 1]이 리턴됩니다. 어떤 의미인지는 아래 설명해봤습니다.

- [1, 1]가 무슨 의미인지 봅시다. 기존 행렬을 다시 상기해봅시다.
[[1, 2],
 [3, 4]]
첫번째 열에서 0번 인덱스는 1, 1번 인덱스는 3입니다.
두번째 열에서 0번 인덱스는 2, 1번 인덱스는 4입니다.
다시 말해 3과 4의 인덱스는 [1, 1]입니다.

In [43]:
print(t)

tensor([[1., 2.],
        [3., 4.]])


만약 두 개를 함께 리턴받는 것이 아니라 max 또는 argmax만 리턴받고 싶다면 다음과 같이 리턴값에도 인덱스를 부여하면 됩니다. 0번 인덱스를 사용하면 max 값만 받아올 수 있고, 1번 인덱스를 사용하면 argmax 값만 받아올 수 있습니다.

In [45]:
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1]) #argmax = max값의 인덱스


Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [46]:
#dim=1로 인자를 주었을 때와 dim=-1로 인자를 주었을 때
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


<h5>4) 뷰(view) - 원소의 수를 유지하면서 텐서의 크기 변경. 중요함</h5>
  
파이토치 텐서의 뷰(View)는 넘파이에서의 리쉐이프(Reshape)와 같은 역할을 합니다. Reshape라는 이름에서 알 수 있듯이, 텐서의 크기(Shape)를 변경해주는 역할을 합니다. 실습을 위해 우선 임의로 다음과 같이 3차원 텐서를 만듭니다.

In [52]:
t = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
ft = torch.FloatTensor(t)

In [53]:
print(ft.shape) #2,2,3이 나온다. 기억해두자

torch.Size([2, 2, 3])


<h5>4-1) 3차원 텐서에서 2차원 텐서로 변경</h5>

In [54]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


view([-1, 3])이 가지는 의미는 이와 같습니다. -1은 첫번째 차원은 사용자가 잘 모르겠으니 파이토치에 맡기겠다는 의미이고, 3은 두번째 차원의 길이는 3을 가지도록 하라는 의미입니다. 다시 말해 현재 3차원 텐서를 2차원 텐서로 변경하되 (?, 3)의 크기로 변경하라는 의미입니다. 결과적으로 (4, 3)의 크기를 가지는 텐서를 얻었습니다.

(2,2,3) -> (2*2,3) - >(4,3)

- view는 기본적으로 변경 전과 변경 후의 텐서 안의 원소의 개수가 유지되어야 함
- 파이토치의 view는 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추

<h5>4-2) 3차원 텐서의 크기 변경 </h5>
  
  이번에는 3차원 텐서에서 3차원 텐서로 차원은 유지하되, 크기(shape)를 바꾸는 작업을 해보겠습니다. view로 텐서의 크기를 변경하더라도 원소의 수는 유지되어야 한다고 언급한 바 있습니다. 그렇다면 (2 × 2 × 3) 텐서를 (? × 1 × 3) 텐서로 변경하라고 하면 ?는 몇 차원인가요?
  
  (2 × 2 × 3) = (? × 1 × 3) = 12를 만족해야 하므로 ?는 4가 됩니다.

In [56]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


<h5>스퀴즈 - 1인 차원을 제거함</h5>
  
  스퀴즈는 차원이 1인 경우에는 해당 차원을 제거합니다.


In [57]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [58]:
print(ft.squeeze())
print(ft.squeeze().shape)


tensor([0., 1., 2.])
torch.Size([3])


<h5>언스퀴즈 - 특정 위치에 1인 차원을 추가한다</h5>
  
언스퀴즈는 스퀴즈와 정반대이다. 특정 위치에 1인 차원을 추가할 수 있다.
실습을 위해 임의로 (3,)의 크기를 갖는 1인 차원 텐서를 만들어보자
  

In [59]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


현재는 차원이 1개인 1차원 벡터입니다. 여기에 첫번째 차원에 1인 차원을 추가해보겠습니다. 첫번째 차원의 인덱스를 의미하는 숫자 0을 인자로 넣으면 첫번째 차원에 1인 차원이 추가됩니다.



In [60]:
print(ft.unsqueeze(0))#인덱스가 0부터 시작하므로 0은 첫번째 차원을 뜻함
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


위 결과는 (3,)의 크기를 가졌던 1차원 벡터가 (1, 3)의 2차원 텐서로 변경된 것을 보여줍니다. 방금 한 연산을 앞서 배운 view로도 구현 가능합니다. 2차원으로 바꾸고 싶으면서 첫번째 차원은 1이기를 원한다면 view에서 (1, -1)을 인자로 사용하면됩니다.

In [62]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


위의 결과는 unsqueeze와 view가 동일한 결과를 만든 것을 보여줍니다. 이번에는 unsqueeze의 인자로 1을 넣어보겠습니다. 인덱스는 0부터 시작하므로 이는 두번째 차원에 1을 추가하겠다는 것을 의미합니다. 현재 크기는 (3,)이었으므로 두번째 차원에 1인 차원을 추가하면 (3, 1)의 크기를 가지게 됩니다. 실습을 진행해보겠습니다.


In [63]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)


tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


이번에는 unsqueeze의 인자로 -1을 넣어보겠습니다. -1은 인덱스 상으로 마지막 차원을 의미합니다. 현재 크기는 (3,)이었으므로 마지막 차원에 1인 차원을 추가하면 (3, 1)의 크기를 가지게 됩니다. 다시 말해 현재 텐서의 경우에는 1을 넣은 경우와 -1을 넣은 경우가 결과가 동일합니다. 실습을 진행해보겠습니다.

In [64]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)


tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


<h5>타입 캐스팅</h5>

In [65]:
lt = torch.LongTensor([1,2,3,4]) # long타입의 lt라는 텐서 선언
print(lt)

tensor([1, 2, 3, 4])


In [66]:
#텐서에 .float()을 붙이면 바로 float으로 형변경
print(lt.float())

tensor([1., 2., 3., 4.])


In [67]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [68]:
#여기에 .long()이라고하면 long 타입의 텐서로 변경되고 .float()이라고 하면 float 타입의 텐서로 변경됩니다.
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


<h5>연결하기</h5>

In [69]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

이제 두 텐서를 torch.cat([ ])를 통해 연결해보겠습니다. 그런데 연결 방법은 한 가지만 있는 것이 아닙니다. torch.cat은 어느 차원을 늘릴 것인지를 인자로 줄 수 있습니다. 예를 들어 dim=0은 첫번째 차원을 늘리라는 의미를 담고있습니다.

In [70]:
print(torch.cat([x,y],dim=0)) # 행갯수증가

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [71]:
print(torch.cat([x,y],dim=1)) # 열갯수증가

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


딥 러닝에서는 주로 모델의 입력 또는 중간 연산에서 두 개의 텐서를 연결하는 경우가 많습니다. 두 텐서를 연결해서 입력으로 사용하는 것은 두 가지의 정보를 모두 사용한다는 의미를 가지고 있습니다.


<h5>스택킹</h5>
연결(concatenate)을 하는 또 다른 방법으로 스택킹(Stacking)이 있습니다. 스택킹은 영어로 쌓는다는 의미입니다. 때로는 연결을 하는 것보다 스택킹이 더 편리할 때가 있는데, 이는 스택킹이 많은 연산을 포함하고 있기 때문입니다.

In [72]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [73]:
print(torch.stack([x,y,z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


스택킹은 사실 많은 연산을 한 번에 축약하고 있습니다. 예를 들어 위 작업은 아래의 코드와 동일한 작업입니다.

In [75]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))
#unsqueeze : 차원을 더 늘림 (1->2), cat: dim=0에 맞춰 병합

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


x, y, z는 기존에는 전부 (2,)의 크기를 가졌습니다. 그런데 .unsqueeze(0)을 하므로서 3개의 벡터는 전부 (1, 2)의 크기의 2차원 텐서로 변경됩니다. 여기에 연결(concatenate)를 의미하는 cat을 사용하면 (3 x 2) 텐서가 됩니다

스택킹에 추가적으로 dim을 인자로 줄 수도 있습니다. 이번에는 dim=1 인자를 주겠습니다.
이는 두번째 차원이 증가하도록 쌓으라는 의미로 해석할 수 있습니다.

In [76]:
print(torch.stack([x, y, z], dim=1))


tensor([[1., 2., 3.],
        [4., 5., 6.]])


<h5>10) ones_like와 zeros_like - 0으로 채워진 텐서와 1로 채워진 텐서</h5>
  

In [77]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)


tensor([[0., 1., 2.],
        [2., 1., 0.]])


위 텐서에 ones_like를 하면 동일한 크기(shape)지만 1으로만 값이 채워진 텐서를 생성합니다.



In [78]:
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기


tensor([[1., 1., 1.],
        [1., 1., 1.]])


위 텐서에 zeros_like를 하면 동일한 크기(shape)지만 0으로만 값이 채워진 텐서를 생성합니다.



In [79]:
print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기


tensor([[0., 0., 0.],
        [0., 0., 0.]])


<h5>In - place Operation (덮어쓰기 연산)</h5>

In [81]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [83]:
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


첫번째 출력은 곱하기 2가 수행된 결과를 보여주고, 두번째 출력은 기존의 값이 그대로 출력된 것을 확인할 수 있습니다. 곱하기 2를 수행했지만 이를 x에다가 다시 저장하지 않았으니, 곱하기 연산을 하더라도 기존의 값 x는 변하지 않는 것이 당연합니다.

그런데 연산 뒤에 _를 붙이면 기존의 값을 덮어쓰기 합니다.



In [84]:
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) # 기존의 값 출력


tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
