<h3>02.nn.module로 구현하는 로지스틱 회귀</h3>


<h4>1. 파이토치의 nn.Linear와 nn.sigmoid로 로지스틱 회귀 구현하기</h4>

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)

In [2]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

nn.Sequential()은 nn.Module 층을 차례로 쌓을 수 있도록 합니다. 뒤에서 이를 이용해서 인공 신경망을 구현하게 되므로 기억하고 있으면 좋습니다. 조금 쉽게 말해서 nn.Sequential()은 Wx+b와 같은 수식과 시그모이드 함수 등과 같은 여러 함수들을 연결해주는 역할을 합니다. 이를 이용해서 로지스틱 회귀를 구현해봅시다

In [3]:
model = nn.Sequential(
   nn.Linear(2, 1), # input_dim = 2, output_dim = 1
   nn.Sigmoid() # 출력은 시그모이드 함수를 거친다
)

In [4]:
model(x_train)

tensor([[0.4020],
        [0.4147],
        [0.6556],
        [0.5948],
        [0.6788],
        [0.8061]], grad_fn=<SigmoidBackward0>)

In [5]:
#optimizer
optimizer = optim.SGD(model.parameters(),lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs +1):

    #H(x)계산
    hypothesis = model(x_train)

    #cost
    cost = F.binary_cross_entropy_with_logits(hypothesis,y_train)

    #cost로 H(x)계산

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    # 20번마다 로그 출력
    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5]) # 예측값이 0.5를 넘으면 True로 간주
        correct_prediction = prediction.float() == y_train # 실제값과 일치하는 경우만 True로 간주
        accuracy = correct_prediction.sum().item() / len(correct_prediction) # 정확도를 계산
        print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format( # 각 에포크마다 정확도를 출력
            epoch, nb_epochs, cost.item(), accuracy * 100,))


Epoch    0/1000 Cost: 0.688104 Accuracy 83.33%
Epoch   10/1000 Cost: 0.659775 Accuracy 83.33%
Epoch   20/1000 Cost: 0.646509 Accuracy 83.33%
Epoch   30/1000 Cost: 0.638818 Accuracy 83.33%
Epoch   40/1000 Cost: 0.633647 Accuracy 83.33%
Epoch   50/1000 Cost: 0.629812 Accuracy 83.33%
Epoch   60/1000 Cost: 0.626758 Accuracy 83.33%
Epoch   70/1000 Cost: 0.624178 Accuracy 83.33%
Epoch   80/1000 Cost: 0.621879 Accuracy 83.33%
Epoch   90/1000 Cost: 0.619724 Accuracy 83.33%
Epoch  100/1000 Cost: 0.617606 Accuracy 83.33%
Epoch  110/1000 Cost: 0.615435 Accuracy 83.33%
Epoch  120/1000 Cost: 0.613138 Accuracy 83.33%
Epoch  130/1000 Cost: 0.610661 Accuracy 83.33%
Epoch  140/1000 Cost: 0.607982 Accuracy 83.33%
Epoch  150/1000 Cost: 0.605115 Accuracy 83.33%
Epoch  160/1000 Cost: 0.602108 Accuracy 83.33%
Epoch  170/1000 Cost: 0.599027 Accuracy 83.33%
Epoch  180/1000 Cost: 0.595938 Accuracy 83.33%
Epoch  190/1000 Cost: 0.592895 Accuracy 83.33%
Epoch  200/1000 Cost: 0.589938 Accuracy 100.00%
Epoch  210/1

In [6]:
print(list(model.parameters()))

[Parameter containing:
tensor([[2.2523, 0.9249]], requires_grad=True), Parameter containing:
tensor([-10.0531], requires_grad=True)]
